# GNU Plot script for episode rewards
# First, create a data file with the episode numbers and rewards
# Generated by claude sonnet 4

# Set terminal and output
set terminal pngcairo enhanced color size 1200,800
set output 'episode_rewards.png'

# Set title and labels
set title "Episode Rewards Over Time" font ",16"
set xlabel "Episode Number" font ",14"
set ylabel "Reward" font ",14"

# Set grid for better readability
set grid

# Set line style
set style line 1 linecolor rgb '#2E86AB' linewidth 2 pointtype 7 pointsize 0.8

# Plot the data
plot 'logs/0th-0_1-0_001.txt' using 1:2 with linespoints linestyle 1 title "Rewards"
